version: '3'

services:

  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    volumes:
      - 'mysql_data:/var/lib/mysql'

  prestashop:
    image: prestashop/prestashop:1.7
    ports:
      - '80:8069'
    environment:
      - DB_SERVER=mysqldb
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - DB_NAME=prestashop
      - ADMIN_PASSWD=admin
      - PS_LANGUAGE=fr
      - PS_COUNTRY=FR
    depends_on:
      - mysqldb

volumes:
  mysql_data:
    driver: local